"use client"

import { useState, useEffect } from "react"
import Image from "next/image"
import { useParams } from "next/navigation"
import { MessageCircle, ArrowLeft, Check } from "lucide-react"
import Link from "next/link"
import QuoteForm from "@/components/quote-form"
import ProductSchema from "@/components/seo/product-schema"

// Product data (would be fetched from an API in production)
const products = [
  {
    id: "1",
    name: "Monocrystalline Solar Panels",
    image: "/placeholder.svg?height=600&width=600",
    description: "High-efficiency monocrystalline solar panels with advanced cell technology for maximum power output.",
    longDescription:
      "Our monocrystalline solar panels are designed to provide maximum efficiency and durability. Made with high-quality silicon cells, these panels can convert more sunlight into electricity compared to other types of panels. The sleek black design not only looks premium but also helps in absorbing more sunlight. These panels are ideal for both residential and commercial installations where space efficiency is important.",
    features: [
      "Efficiency: 20-22%",
      "Power Output: 330W-450W",
      "Warranty: 25 years performance, 10 years product",
      "Temperature Coefficient: -0.35%/°C",
      "Cell Type: Monocrystalline PERC",
    ],
    specifications: [
      { name: "Dimensions", value: "1700 x 1000 x 35 mm" },
      { name: "Weight", value: "18-20 kg" },
      { name: "Operating Temperature", value: "-40°C to +85°C" },
      { name: "Maximum System Voltage", value: "1000V DC (IEC)" },
      { name: "Frame", value: "Anodized Aluminum Alloy" },
      { name: "Front Glass", value: "3.2mm High Transmission, Low Iron, Tempered Glass" },
      { name: "Junction Box", value: "IP68 Rated" },
      { name: "Certificates", value: "IEC 61215, IEC 61730, UL 1703" },
    ],
    applications: [
      "Residential Rooftop Solar Systems",
      "Commercial Buildings",
      "Industrial Facilities",
      "Solar Farms",
      "Off-grid Solar Systems",
    ],
    relatedProducts: [2, 3, 7],
  },
  {
    id: "2",
    name: "Grid-Tied Solar Inverters",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Advanced grid-tied inverters that convert DC electricity from solar panels into AC electricity for home use and grid export.",
    longDescription:
      "Our grid-tied solar inverters are designed to efficiently convert the DC power generated by your solar panels into AC power that can be used in your home or exported to the grid. These inverters feature advanced MPPT (Maximum Power Point Tracking) technology to ensure maximum energy harvest from your solar panels. With built-in monitoring capabilities, you can track your system's performance in real-time through a smartphone app or web portal.",
    features: [
      "Efficiency: 97-98%",
      "Power Range: 1kW-10kW",
      "Warranty: 5-10 years",
      "MPPT Channels: 2-4",
      "Monitoring: Built-in WiFi/Ethernet",
    ],
    specifications: [
      { name: "Dimensions", value: "450 x 370 x 160 mm" },
      { name: "Weight", value: "15-25 kg" },
      { name: "Operating Temperature", value: "-25°C to +60°C" },
      { name: "Maximum Input Voltage", value: "1000V DC" },
      { name: "MPPT Voltage Range", value: "160V-800V DC" },
      { name: "Output Voltage", value: "230V AC, 50Hz" },
      { name: "Protection Degree", value: "IP65" },
      { name: "Certificates", value: "IEC 62109-1/2, VDE 0126-1-1, G83/2, AS4777" },
    ],
    applications: [
      "Residential Grid-Connected Systems",
      "Commercial Solar Installations",
      "Solar Carports",
      "Building Integrated Photovoltaics",
      "Small to Medium Solar Farms",
    ],
    relatedProducts: [1, 3, 5],
  },
  {
    id: "3",
    name: "Lithium-Ion Solar Batteries",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "High-capacity lithium-ion batteries for energy storage, allowing you to use solar power even when the sun isn't shining.",
    longDescription:
      "Our lithium-ion solar batteries provide reliable energy storage for your solar system, allowing you to store excess energy generated during the day for use during the night or during power outages. These batteries feature advanced battery management systems (BMS) that ensure safe operation, optimal charging/discharging, and long battery life. With their compact design and high energy density, they can be easily installed in homes and businesses.",
    features: [
      "Capacity: 5kWh-15kWh",
      "Cycle Life: 6000+ cycles",
      "Warranty: 10 years",
      "DoD (Depth of Discharge): 95%",
      "Scalable: Yes, up to 45kWh",
    ],
    specifications: [
      { name: "Dimensions", value: "600 x 500 x 200 mm" },
      { name: "Weight", value: "50-80 kg" },
      { name: "Operating Temperature", value: "-10°C to +50°C" },
      { name: "Nominal Voltage", value: "48V DC" },
      { name: "Battery Type", value: "Lithium Iron Phosphate (LiFePO4)" },
      { name: "Communication", value: "CAN, RS485" },
      { name: "Protection Degree", value: "IP55" },
      { name: "Certificates", value: "IEC 62619, UL 1973, UN38.3" },
    ],
    applications: [
      "Residential Energy Storage",
      "Off-Grid Solar Systems",
      "Backup Power Systems",
      "Peak Shaving for Commercial Buildings",
      "Microgrids",
    ],
    relatedProducts: [1, 2, 8],
  },
  {
    id: "4",
    name: "Solar Water Heaters",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Efficient solar water heating systems that use the sun's energy to heat water for residential and commercial use.",
    longDescription:
      "Our solar water heaters provide an eco-friendly and cost-effective solution for your hot water needs. Using evacuated tube collectors, these systems efficiently capture solar energy to heat water, even on cloudy days. The well-insulated storage tank ensures that the water stays hot for extended periods. With minimal maintenance requirements and long operational life, our solar water heaters offer significant savings on your energy bills while reducing your carbon footprint.",
    features: [
      "Capacity: 100L-300L",
      "Type: Evacuated Tube Collector",
      "Warranty: 7 years",
      "Auxiliary Heating: Electric Backup",
      "Insulation: PUF Insulation",
    ],
    specifications: [
      { name: "Tank Material", value: "SUS304 Stainless Steel" },
      { name: "Insulation Thickness", value: "50mm PUF" },
      { name: "Number of Tubes", value: "15-30 (depending on capacity)" },
      { name: "Tube Dimensions", value: "58mm x 1800mm" },
      { name: "Working Pressure", value: "0.6 MPa" },
      { name: "Auxiliary Heating", value: "2kW Electric Element" },
      { name: "Stand Material", value: "Galvanized Steel" },
      { name: "Certificates", value: "IS 12933, MNRE Approved" },
    ],
    applications: [
      "Residential Hot Water",
      "Hotels and Guesthouses",
      "Hospitals",
      "Swimming Pools",
      "Industrial Process Heating",
    ],
    relatedProducts: [1, 5, 10],
  },
  {
    id: "5",
    name: "Solar Charge Controllers",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "MPPT and PWM charge controllers that regulate the voltage and current coming from solar panels to safely charge batteries.",
    longDescription:
      "Our solar charge controllers are essential components for any off-grid or hybrid solar system with battery storage. We offer both MPPT (Maximum Power Point Tracking) and PWM (Pulse Width Modulation) controllers to suit different system requirements and budgets. MPPT controllers provide higher efficiency by optimizing the voltage from the solar panels to match the battery requirements, while PWM controllers offer a more cost-effective solution for smaller systems. All our controllers feature comprehensive protection functions and clear LCD displays for system monitoring.",
    features: [
      "Type: MPPT/PWM",
      "Current Rating: 10A-60A",
      "Voltage: 12V/24V/48V Auto Detect",
      "Efficiency: Up to 99% for MPPT",
      "Display: LCD with system parameters",
    ],
    specifications: [
      { name: "Dimensions", value: "Varies by model" },
      { name: "Weight", value: "1-3 kg" },
      { name: "Operating Temperature", value: "-20°C to +55°C" },
      { name: "Maximum PV Input Voltage", value: "150V (MPPT), 50V (PWM)" },
      { name: "Battery Types", value: "Lead Acid, Gel, AGM, Lithium" },
      { name: "Protection", value: "Overcharge, Over-discharge, Short Circuit, Reverse Polarity" },
      { name: "Communication", value: "RS485, Bluetooth (select models)" },
      { name: "Certificates", value: "CE, RoHS" },
    ],
    applications: [
      "Off-Grid Solar Systems",
      "RV and Boat Solar Systems",
      "Backup Power Systems",
      "Remote Monitoring Stations",
      "Telecommunication Towers",
    ],
    relatedProducts: [1, 3, 8],
  },
  {
    id: "6",
    name: "Solar Water Pumps",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Energy-efficient solar water pumps for irrigation, drinking water, and other applications in areas with limited or no grid access.",
    longDescription:
      "Our solar water pumping systems provide a reliable and sustainable solution for water supply needs in areas with limited or no access to the electrical grid. These systems use solar energy to power efficient DC or AC pumps, eliminating the need for fuel and reducing operating costs. We offer surface pumps for shallow water sources and submersible pumps for deep wells. Each system comes with a specialized controller that optimizes the pump's performance based on available sunlight and protects the pump from damage due to dry running or other adverse conditions.",
    features: [
      "Power: 1HP-10HP",
      "Max Head: Up to 100m",
      "Flow Rate: Up to 300 LPM",
      "Type: Submersible/Surface",
      "Controller: Built-in MPPT",
    ],
    specifications: [
      { name: "Pump Type", value: "Centrifugal, Helical Rotor" },
      { name: "Motor Type", value: "BLDC/AC (with VFD)" },
      { name: "Solar Array Size", value: "750W-7500W" },
      { name: "Operating Voltage", value: "48V-380V DC/AC" },
      { name: "Material", value: "Stainless Steel, Cast Iron" },
      { name: "Protection", value: "Dry Run, Overload, Lightning" },
      { name: "Monitoring", value: "Flow, Pressure, Power (select models)" },
      { name: "Certificates", value: "IS 14220, MNRE Approved" },
    ],
    applications: [
      "Agricultural Irrigation",
      "Drinking Water Supply",
      "Livestock Watering",
      "Fish Farming",
      "Industrial Water Supply",
    ],
    relatedProducts: [1, 5, 9],
  },
  {
    id: "7",
    name: "Polycrystalline Solar Panels",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Cost-effective polycrystalline solar panels with good efficiency and performance for larger installations where space is not a constraint.",
    longDescription:
      "Our polycrystalline solar panels offer a cost-effective solution for solar energy generation. While slightly less efficient than monocrystalline panels, they provide excellent value for money and are ideal for larger installations where space is not a major constraint. These panels have a distinctive blue appearance due to the multiple crystal structure and are manufactured using high-quality materials to ensure durability and long-term performance. Each panel undergoes rigorous testing to meet international quality standards and comes with comprehensive warranty coverage.",
    features: [
      "Efficiency: 16-18%",
      "Power Output: 280W-330W",
      "Warranty: 25 years performance, 10 years product",
      "Temperature Coefficient: -0.40%/°C",
      "Cell Type: Polycrystalline Silicon",
    ],
    specifications: [
      { name: "Dimensions", value: "1650 x 992 x 35 mm" },
      { name: "Weight", value: "18-19 kg" },
      { name: "Operating Temperature", value: "-40°C to +85°C" },
      { name: "Maximum System Voltage", value: "1000V DC (IEC)" },
      { name: "Frame", value: "Anodized Aluminum Alloy" },
      { name: "Front Glass", value: "3.2mm Tempered Glass" },
      { name: "Junction Box", value: "IP67 Rated" },
      { name: "Certificates", value: "IEC 61215, IEC 61730, UL 1703" },
    ],
    applications: [
      "Large-Scale Solar Farms",
      "Commercial Rooftop Installations",
      "Ground-Mounted Systems",
      "Carports and Parking Structures",
      "Agricultural Applications",
    ],
    relatedProducts: [1, 2, 9],
  },
  {
    id: "8",
    name: "Hybrid Solar Inverters",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Versatile hybrid inverters that can work with both the grid and batteries, providing backup power during outages and optimizing solar energy usage.",
    longDescription:
      "Our hybrid solar inverters combine the functionality of grid-tied inverters and battery inverters in a single unit, offering the best of both worlds. These advanced inverters can direct solar power to your home, feed excess energy to the grid, and charge batteries for later use. During power outages, they automatically switch to battery power to keep essential loads running. With intelligent energy management capabilities, hybrid inverters can prioritize self-consumption, time-of-use optimization, or backup power based on your preferences. The built-in monitoring system allows you to track energy flows and system performance in real-time.",
    features: [
      "Power Range: 3kW-10kW",
      "Battery Compatibility: 48V Lithium/Lead-Acid",
      "Efficiency: 96-98%",
      "MPPT Channels: 2-3",
      "Backup Power: Yes, with seamless transfer",
    ],
    specifications: [
      { name: "Dimensions", value: "500 x 450 x 180 mm" },
      { name: "Weight", value: "25-35 kg" },
      { name: "Operating Temperature", value: "-20°C to +60°C" },
      { name: "PV Input Voltage Range", value: "120V-800V DC" },
      { name: "Battery Voltage Range", value: "40V-60V DC" },
      { name: "AC Output", value: "230V, 50Hz, Single Phase" },
      { name: "Protection Degree", value: "IP65" },
      { name: "Certificates", value: "IEC 62109-1/2, IEC 62477, G99" },
    ],
    applications: [
      "Residential Solar + Storage Systems",
      "Small Businesses with Critical Loads",
      "Areas with Frequent Power Outages",
      "Off-Grid Applications with Occasional Grid Access",
      "Energy Arbitrage in Time-of-Use Billing Areas",
    ],
    relatedProducts: [1, 3, 5],
  },
  {
    id: "9",
    name: "Solar Panel Mounting Structures",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Durable and easy-to-install mounting structures for rooftop and ground-mounted solar panel installations, designed to withstand harsh weather conditions.",
    longDescription:
      "Our solar panel mounting structures provide a secure and optimized foundation for your solar panels. We offer a variety of mounting solutions for different roof types (flat, sloped, metal, concrete) and ground-mounted installations. Each structure is engineered to withstand local wind and snow loads while maintaining the optimal tilt angle for maximum solar energy production. Made from high-quality aluminum and stainless steel components, our mounting structures are corrosion-resistant and designed for a service life that matches or exceeds that of the solar panels. The modular design allows for quick and easy installation, reducing labor costs.",
    features: [
      "Material: Anodized Aluminum/Hot-Dipped Galvanized Steel",
      "Wind Load Capacity: Up to 180 km/h",
      "Snow Load Capacity: Up to 2.5 kN/m²",
      "Tilt Angle: Adjustable 10-30° (roof) / 15-45° (ground)",
      "Warranty: 15 years structural",
    ],
    specifications: [
      { name: "Rail Thickness", value: "2.0-3.0 mm" },
      { name: "Fastener Material", value: "Stainless Steel 304/A2-70" },
      { name: "Grounding", value: "Integrated grounding pins/clips" },
      { name: "Roof Attachment", value: "Roof hooks, L-feet, or ballast blocks" },
      { name: "Ground Foundation", value: "Concrete foundation or ground screws" },
      { name: "Panel Arrangement", value: "Portrait or landscape orientation" },
      { name: "Compatibility", value: "All standard framed solar panels" },
      { name: "Certificates", value: "IS 800, IS 801, IS 806, IS 808" },
    ],
    applications: [
      "Residential Rooftop Installations",
      "Commercial Flat Roof Systems",
      "Ground-Mounted Solar Arrays",
      "Carports and Shade Structures",
      "Solar Farms",
    ],
    relatedProducts: [1, 7, 10],
  },
  {
    id: "10",
    name: "Solar Street Lights",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Standalone solar-powered street lights with integrated panels, batteries, and efficient LED luminaires for roads, pathways, and public spaces.",
    longDescription:
      "Our solar street lighting systems provide reliable, energy-efficient illumination for roads, pathways, parks, and other public spaces without the need for grid connection. Each unit is a complete standalone system with solar panels, battery storage, intelligent controller, and high-efficiency LED luminaire. The smart controller adjusts brightness based on battery level and can be programmed for different lighting schedules to maximize battery life during extended cloudy periods. Motion sensors can be added to increase brightness when activity is detected, further enhancing energy efficiency. These lights are ideal for remote locations, new developments without established infrastructure, and areas seeking to reduce electricity costs.",
    features: [
      "LED Power: 15W-120W",
      "Solar Panel: 50W-300W",
      "Battery: LiFePO4, 12V/24V, 30Ah-200Ah",
      "Lighting Time: Up to 14 hours/night",
      "Pole Height: 3m-9m",
    ],
    specifications: [
      { name: "Luminaire Efficiency", value: ">160 lm/W" },
      { name: "Color Temperature", value: "4000K-6000K" },
      { name: "Battery Life", value: "2000+ cycles (>5 years)" },
      { name: "Controller", value: "MPPT with time/motion control" },
      { name: "Pole Material", value: "Hot-dipped galvanized steel" },
      { name: "Protection Degree", value: "IP66 for luminaire, IP65 for battery box" },
      { name: "Operating Temperature", value: "-20°C to +60°C" },
      { name: "Certificates", value: "IS 16111, IEC 62124, LM-79, LM-80" },
    ],
    applications: [
      "Rural Road Lighting",
      "Urban Street Lighting",
      "Park and Pathway Illumination",
      "Parking Lot Lighting",
      "Security Lighting for Remote Facilities",
    ],
    relatedProducts: [3, 5, 9],
  },
  {
    id: "11",
    name: "Solar DC Refrigerators",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Energy-efficient DC refrigerators and freezers powered directly by solar panels, ideal for off-grid homes, medical facilities, and remote locations.",
    longDescription:
      "Our solar DC refrigerators and freezers are specifically designed for off-grid applications where reliable cooling is essential. These units operate directly on DC power from solar panels and batteries, eliminating the efficiency losses associated with DC-to-AC conversion in conventional refrigerators. The highly efficient compressors and enhanced insulation allow these refrigerators to maintain stable temperatures with minimal energy consumption. Many models can run for multiple days on battery power during cloudy weather. These refrigerators are ideal for rural homes, medical facilities storing vaccines, eco-tourism lodges, and remote research stations where reliable refrigeration is critical but grid power is unavailable or unreliable.",
    features: [
      "Capacity: 50L-300L",
      "Power Consumption: 0.3-1.2 kWh/day",
      "Voltage: 12V/24V DC",
      "Temperature Range: 2°C to 8°C (refrigerator) / -18°C to -25°C (freezer)",
      "Insulation: High-density PU foam, 60-100mm",
    ],
    specifications: [
      { name: "Compressor", value: "SECOP/Danfoss DC compressor" },
      { name: "Refrigerant", value: "R-134a or R-600a (eco-friendly)" },
      { name: "Climate Class", value: "T (tropical), operates up to 43°C ambient" },
      { name: "Controls", value: "Digital thermostat with LED display" },
      { name: "Battery Protection", value: "Low voltage disconnect" },
      { name: "Construction", value: "Powder-coated steel exterior, aluminum interior" },
      { name: "Additional Features", value: "Interior LED lighting, adjustable shelves" },
      { name: "Certificates", value: "WHO PQS (select models), Energy Star" },
    ],
    applications: [
      "Off-Grid Homes and Cabins",
      "Medical Facilities for Vaccine Storage",
      "Remote Research Stations",
      "Eco-Tourism Lodges",
      "Mobile Clinics and Disaster Relief",
    ],
    relatedProducts: [1, 3, 8],
  },
  {
    id: "12",
    name: "Solar Home Lighting Systems",
    image: "/placeholder.svg?height=600&width=600",
    description:
      "Complete solar home lighting kits with panels, battery, controller, and LED lights for homes and small businesses without reliable grid access.",
    longDescription:
      "Our solar home lighting systems provide a complete lighting solution for homes, shops, and small businesses in areas with limited or unreliable grid access. Each kit includes solar panels, a battery for energy storage, a charge controller, and energy-efficient LED lights. The systems are designed for easy installation and minimal maintenance, making them accessible to users without technical expertise. The included battery stores enough energy to provide lighting for multiple evenings, even during cloudy weather. These systems significantly improve quality of life by replacing kerosene lamps and candles with clean, bright, and safe lighting while eliminating ongoing fuel costs and reducing fire hazards.",
    features: [
      "Solar Panel: 20W-200W",
      "Battery: 12V, 7Ah-100Ah (Lead-Acid or Lithium)",
      "LED Lights: 3-10 points, 3W-9W each",
      "Runtime: 4-12 hours per day",
      "Additional Features: Mobile charging, DC fan support",
    ],
    specifications: [
      { name: "Light Output", value: "350-900 lumens per light point" },
      { name: "Color Temperature", value: "6000K (cool white)" },
      { name: "Controller Type", value: "PWM with battery protection" },
      { name: "Wiring", value: "Pre-wired with MC4 connectors and switches" },
      { name: "Battery Type", value: "Sealed maintenance-free lead-acid or LiFePO4" },
      { name: "Battery Life", value: "3-5 years (lead-acid), 7-10 years (lithium)" },
      { name: "Expandability", value: "Additional light points and appliances can be added" },
      { name: "Certificates", value: "IEC 62124, Lighting Global certified" },
    ],
    applications: [
      "Rural Homes without Grid Access",
      "Urban Homes with Frequent Power Outages",
      "Small Shops and Businesses",
      "Community Centers and Schools",
      "Temporary Shelters and Relief Camps",
    ],
    relatedProducts: [1, 3, 5],
  },
]

export default function ProductDetailPage() {
  const params = useParams()
  const [product, setProduct] = useState(null)
  const [showQuoteForm, setShowQuoteForm] = useState(false)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    // Simulate API fetch
    const fetchProduct = () => {
      setLoading(true)
      setTimeout(() => {
        const foundProduct = products.find((p) => p.id === params.id)
        setProduct(foundProduct || null)
        setLoading(false)
      }, 500)
    }

    fetchProduct()
  }, [params.id])

  if (loading) {
    return (
      <div className="pt-32 pb-16 min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  if (!product) {
    return (
      <div className="pt-32 pb-16 min-h-screen">
        <div className="container-custom text-center">
          <h1 className="mb-4">Product Not Found</h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto mb-8">
            The product you are looking for does not exist or has been removed.
          </p>
          <Link href="/products" className="btn-primary">
            <ArrowLeft className="mr-2 h-5 w-5" />
            Back to Products
          </Link>
        </div>
      </div>
    )
  }

  return (
    <>
      {/* Product Detail */}
      <section className="pt-32 pb-16">
        <div className="container-custom">
          <div className="mb-8">
            <Link href="/products" className="inline-flex items-center text-blue-600 hover:underline">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Products
            </Link>
          </div>

          <div className="grid md:grid-cols-2 gap-8 lg:gap-12">
            {/* Product Image */}
            <div className="relative h-[300px] md:h-[500px] rounded-2xl overflow-hidden">
              <Image src={product.image || "/placeholder.svg"} alt={product.name} fill className="object-cover" />
            </div>

            {/* Product Info */}
            <div>
              <h1 className="text-3xl md:text-4xl font-bold mb-4">{product.name}</h1>
              <p className="text-gray-600 mb-6">{product.description}</p>

              <h2 className="text-xl font-bold mb-3">Key Features</h2>
              <ul className="space-y-2 mb-6">
                {product.features.map((feature, index) => (
                  <li key={index} className="flex items-start">
                    <Check className="h-5 w-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>

              <button onClick={() => setShowQuoteForm(true)} className="btn-primary w-full md:w-auto">
                <MessageCircle className="mr-2 h-5 w-5" />
                Request a Quote
              </button>
            </div>
          </div>

          {/* Product Details Tabs */}
          <div className="mt-16">
            <div className="border-b border-gray-200">
              <nav className="-mb-px flex space-x-8">
                <a
                  href="#description"
                  className="border-blue-600 text-blue-600 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm"
                >
                  Description
                </a>
                <a
                  href="#specifications"
                  className="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm"
                >
                  Specifications
                </a>
                <a
                  href="#applications"
                  className="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm"
                >
                  Applications
                </a>
              </nav>
            </div>

            {/* Description */}
            <div id="description" className="py-8">
              <h2 className="text-2xl font-bold mb-4">Product Description</h2>
              <p className="text-gray-600 mb-4">{product.longDescription}</p>
            </div>

            {/* Specifications */}
            <div id="specifications" className="py-8 border-t border-gray-200">
              <h2 className="text-2xl font-bold mb-4">Technical Specifications</h2>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <tbody className="bg-white divide-y divide-gray-200">
                    {product.specifications.map((spec, index) => (
                      <tr key={index} className={index % 2 === 0 ? "bg-gray-50" : "bg-white"}>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{spec.name}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{spec.value}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Applications */}
            <div id="applications" className="py-8 border-t border-gray-200">
              <h2 className="text-2xl font-bold mb-4">Applications</h2>
              <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {product.applications.map((app, index) => (
                  <li key={index} className="flex items-start">
                    <Check className="h-5 w-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
                    <span>{app}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Related Products */}
          {product.relatedProducts && product.relatedProducts.length > 0 && (
            <div className="mt-16 pt-8 border-t border-gray-200">
              <h2 className="text-2xl font-bold mb-8">Related Products</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {product.relatedProducts.map((relatedId) => {
                  const relatedProduct = products.find((p) => p.id === relatedId.toString())
                  if (!relatedProduct) return null

                  return (
                    <Link key={relatedProduct.id} href={`/products/${relatedProduct.id}`} className="block h-full">
                      <div className="card h-full hover:translate-y-[-5px]">
                        <div className="relative h-48 w-full">
                          <Image
                            src={relatedProduct.image || "/placeholder.svg"}
                            alt={relatedProduct.name}
                            fill
                            className="object-cover rounded-t-2xl"
                          />
                        </div>
                        <div className="p-6">
                          <h3 className="font-bold text-lg mb-2">{relatedProduct.name}</h3>
                          <p className="text-gray-600 line-clamp-2">{relatedProduct.description}</p>
                        </div>
                      </div>
                    </Link>
                  )
                })}
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Quote Form Modal */}
      {showQuoteForm && <QuoteForm productId={Number.parseInt(product.id)} onClose={() => setShowQuoteForm(false)} />}
      {/* Product Schema */}
      {product && (
        <ProductSchema
          name={product.name}
          description={product.description}
          image={product.image}
          price={Number.parseFloat(product.id) * 100} // Just for demo purposes
          sku={product.id}
          availability="InStock"
        />
      )}
    </>
  )
}

